configfile: "workflow/config/config.yaml"


include: "rules/common.smk"
include: "rules/setup.smk"
include: "rules/hic.smk"

rule all:
    params:

    input:
        [result[0] for result in EXPERIMENTS.FormatTemplate("results/{experiment}/{replicate}/matrix/{replicate}_ds{downsample}.mcool", \
            downsample = config['downsample'])] +
        [result[0] for result in EXPERIMENTS.FormatTemplate("results/{experiment}/matrix/{experiment}_ds{downsample}.mcool", \
            downsample = config['downsample'])]
