configfile: "config/config.yaml"
include: "rules/common.smk"
include: "rules/align.smk"

rule all:
    input:
        [result[0] for result in EXPERIMENTS.FormatTemplate("results/{experiment}/sambam/{replicate}.bam")]
